spring:
  profiles:
    active: "test"

default:
  sender: "igorfoliveira@gmail.com"
  recipient: "igorfoliveira@gmail.com"

jwt:
  secret: TokenEcommerce
  expiration: 86400000

aws:
  access_key_id:
  secret_access_key: 
s3:
  bucket: ionic-spring-boot
  region: sa-east-1