spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: igorfoliveira@gmail.com
    password: // https://support.google.com/accounts/answer/185833 (autenticacao em 2 etapas, gerar senha de app e ativar Acesso a app menos seguro)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: "jdbc:mysql://localhost:3306/ecommerce?&serverTimezone=UTC"
    username: "root"
    password:

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true