spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/ecommerce?&serverTimezone=UTC"
    username: "root"
    password:

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true